global:
  imageOverrides:
    assisted_installer: ''
    assisted_installer_agent: ''
    assisted_installer_controller: ''
    assisted_service: ''
    postgresql_12_centos7: ''
  pullPolicy: Always
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
org: open-cluster-management
