# This is a basic workflow to help you get started with Actions

name: Update Chart

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a set of commands using the runners shell
      - name: Update Chart
        run: |
          make regenerate-chart

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: "manual workflow dispatch: Updating Chart"
          file_pattern: stable/
          skip_fetch: true
          commit_user_name: GitHub Actions
          commit_user_email: noreply@github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>          
    
